### ISSUE TITLE
Unable to login to YouTrack free plan

### ISSUE THREAD

**Issue by jgesser** [JetBrains/youtrack.mylyn.connector#11]
After the trial period, I have changed my account to the free option.
Even after changing the the url to http (no SSL), the connector does not authenticate my user.
I was working before the free period expire.

Is there any limitation to free accounts?

Thanks!

**Comment by zeckson** [comment]
Hi jgesser,

We have experienced some problems with login recently.
Please try once more, I believe that problem should gone.

**Comment by jgesser** [comment]
Thanks @zeckson . It is working now!
